name: Pull request testing
on:
  pull_request:
    branches: [main]
    paths:
      # Note that when splitting python vs javascript tests, will update this (once python directory is available & JS is moved into top level dir)
      - "**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          yarn install
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
