name: Python Pull request testing
on:
  pull_request:
    branches: [main]
    paths:
      - "python/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd python && pip install -r requirements.txt
      - name: Install lib
        run: |
          cd python && pip install -e .
      - uses: jakebailey/pyright-action@v1
        continue-on-error: true
        with:
          working-directory: "./python"
      - name: Run tests
        run: |
          cd python && pytest
