name: Pull request testing
on:
  pull_request:
    branches: [main]
    paths:
      # Note that when splitting python vs javascript tests, will update this (once python directory is available & JS is moved into top level dir)
      - "python/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd python && pip install -r requirements.txt
      - name: Install lib
        run: |
          cd python && pip install -e .
      - name: Run tests
        run: |
          cd python && pytest
