name: Python Pull request testing
on:
  pull_request:
    branches: [main]
    paths:
      - "python/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd python && pip install -r requirements.txt
      - name: Install lib
        run: |
          cd python && pip install -e .
      - uses: jakebailey/pyright-action@v1
        with:
          working-directory: "./python"
      - name: Run tests
        run: |
          pytest

      # TODO: This will need to move into separate workflow that is on push to main rather than on each PR
      # Also will want to use matrix strategy to build for different platforms: See https://github.com/pypa/cibuildwheel#example-setup
      # - name: Install cibuildwheel
      #   run: cd python && python -m pip install cibuildwheel==2.16.2

      # - name: Build wheels
      #   run: cd python && python -m cibuildwheel --output-dir wheelhouse
      #   # to supply options, put them in 'env', like:
      #   # env:
      #   #   CIBW_SOME_OPTION: value

      # Got this error with cibuildwheel:  cibuildwheel: Build failed because a pure Python wheel was generated.
      # If you intend to build a pure-Python wheel, you don't need cibuildwheel - use
      # `pip wheel -w DEST_DIR .` instead.
      - name: Build wheels
        run: cd python && pip wheel -w wheelhouse .

      - uses: actions/upload-artifact@v3
        with:
          path: ./python/wheelhouse/*.whl
          retention-days: 30 # Optional
